apiVersion: v1
kind: Service
metadata:
  name: clusterip-nodeport-service
spec:
  clusterIP: None # <= Don't forget!!
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: headless-deployment