apiVersion: v1
kind: Service
metadata:
  name: webapp1-nodeport-svc
  labels:
    app: webapp1-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: webapp1-nodeport
---
kind: Deployment 
apiVersion: apps/v1
metadata:
  name: webapp1-nodeport
  # labels:   not mandatory 
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: webapp1-nodeport
  template:   # pod template which need to be created, which include always about the pod metadata & spec
    metadata:
      #name: test
      labels: 
        app: webapp1-nodeport
  spec:
    containers:
      - name: webapp1-nodeport-pod
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
---