kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1-pvc
  labels:
    type: local
spec:
  volumeName: pv1   ## must be the pv name that you want to claim
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce